import random
from game_components import Character
from room_generator import RoomGenerator

def stat_gen(stat_precedence: dict, level: int) -> dict:
    """
    Generates the statistics for a character using
    the given precedence for stats.

    Args:
    stat_precedence: a dictionary of three strings consisting of
    combat_skill, defense, and speed with precedence as their
    value.  Precedence is a value determining how strong a
    statistic will be, the higher the better range should be
    from 0-10.
    level: an int that helps balance character generation
    statistics and represents the level of the character being
    generated

    Returns:
    A dictionary of the statistics generated and their
    associated score.
    """
    stat_final = {}
    for stat in stat_precedence:
        prec = stat_precedence[stat]
        if prec < 1:
            prec = 1
        stat_final[stat] = random.randrange(1, prec)+(level)
    return stat_final
def char_gen(stat_list: list, start_room: RoomGenerator.Room) -> Character:
    """
    Generates the character object for the player specifically
    and the statistics associated.

    Args:
    stat_list: list of the order of stats the the user inputs

    Returns:
    The character object generated by user response.
    """
    combat = 10-2*(stat_list.index('combat')+1)
    defense = 10-2*(stat_list.index('defense')+1)
    speed = 10-2*(stat_list.index('speed')+1)
    stat_prec = {'combat':combat, 'def':defense, 'speed':speed}
    stat_final = stat_gen(stat_prec, 1)
    char = Character('You', start_room, stat_final['combat'], stat_final['def'], stat_final['speed'])
    return char
